# Generated by Django 5.0.6 on 2024-07-07 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_teacherdata_about_teacherdata_prefered_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admindata',
            name='about',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='studentdata',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.teacherdata'),
        ),
    ]
